// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteAPI.DATA;

#nullable disable

namespace RestauranteAPI.Migrations
{
    [DbContext(typeof(APIDbContext))]
    [Migration("20240204181852_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestauranteAPI.MODELS.Platos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("TipoComidaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TipoComidaID");

                    b.ToTable("Platos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nombre = "LaSagna",
                            Precio = 10.0,
                            TipoComidaID = 1
                        },
                        new
                        {
                            ID = 2,
                            Nombre = "Tacos",
                            Precio = 8.5,
                            TipoComidaID = 2
                        },
                        new
                        {
                            ID = 3,
                            Nombre = "Hamburguesa",
                            Precio = 7.5,
                            TipoComidaID = 3
                        },
                        new
                        {
                            ID = 4,
                            Nombre = "Guatita",
                            Precio = 9.0,
                            TipoComidaID = 4
                        },
                        new
                        {
                            ID = 5,
                            Nombre = "Ceviche",
                            Precio = 5.0,
                            TipoComidaID = 5
                        });
                });

            modelBuilder.Entity("RestauranteAPI.MODELS.TipoComida", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TipoComida");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripcion = "Italiana"
                        },
                        new
                        {
                            ID = 2,
                            Descripcion = "Mexicana"
                        },
                        new
                        {
                            ID = 3,
                            Descripcion = "Americana"
                        },
                        new
                        {
                            ID = 4,
                            Descripcion = "Ecuatoriana"
                        },
                        new
                        {
                            ID = 5,
                            Descripcion = "Colombiana"
                        });
                });

            modelBuilder.Entity("RestauranteAPI.MODELS.Platos", b =>
                {
                    b.HasOne("RestauranteAPI.MODELS.TipoComida", "TipoComida")
                        .WithMany("Platos")
                        .HasForeignKey("TipoComidaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoComida");
                });

            modelBuilder.Entity("RestauranteAPI.MODELS.TipoComida", b =>
                {
                    b.Navigation("Platos");
                });
#pragma warning restore 612, 618
        }
    }
}
